# find_trending_companies:
#   description: >
#     Find the top trending companies in the news in {sector} by searching the latest news.
#     Only return **valid JSON** that strictly follows this schema:
#     {
#       "companies": [
#         {
#           "name": "Company Name",
#           "ticker": "TICKER",
#           "reason": "Why this company is trending in the news"
#         }
#       ]
#     }
#     The top-level "companies" field must always be a list, even if there is only one company.
#     Do NOT wrap the JSON in quotes or markdown code fences.
#     Do NOT include extra commentary, text, or explanations.
#   expected_output: >
#     A JSON object with a "companies" field that contains a list of companies, 
#     each with "name", "ticker", and "reason".
#   agent: trending_company_finder
#   output_file: output/trending_companies.json

# research_trending_companies:
#   description: >
#     Given the trending companies found earlier, provide detailed analysis of each company
#     by searching online. Return the results as **valid JSON** that strictly follows this schema:
#     {
#       "research_list": [
#         {
#           "name": "Company Name",
#           "market_position": "Current market position and competition",
#           "future_outlook": "Future outlook and growth prospects",
#           "investment_potential": "Investment potential and suitability for investors"
#         }
#       ]
#     }
#     The top-level "research_list" field must always be a list, even if there is only one company.
#     Do NOT wrap the JSON in quotes or markdown code fences.
#     Do NOT include extra commentary, text, or explanations.
#   expected_output: >
#     A JSON object with a "research_list" field containing detailed research
#     for each company with name, market_position, future_outlook, and investment_potential.
#   agent: financial_researcher
#   context:
#     - find_trending_companies
#   output_file: output/research_report.json

# pick_best_company:
#   description: >
#     Analyze the research findings and pick the single best company for investment.
#     Send a push notification to the user with the decision and a 1-sentence rationale.
#     Then respond with a detailed report in valid Markdown format explaining:
#       - Why this company was chosen
#       - Why the other companies were not selected
#     Do NOT include extra commentary or text outside of the Markdown structure.
#   expected_output: >
#     A Markdown report with:
#     - The chosen company and why it was chosen
#     - The companies that were not selected and why they were not selected
#   agent: stock_picker
#   context:
#     - research_trending_companies
#   output_file: output/decision.md

find_trending_companies:
  description: >
    Find the top trending companies in the news in {sector} by searching the latest news.
    Provide the results as a clean, human-readable list in plain text or Markdown.
    Each entry should include:
      - Company name
      - Ticker (if available)
      - Reason why the company is trending in the news
  expected_output: >
    A plain text or Markdown list of trending companies with their names, tickers, 
    and reasons for trending.
  agent: trending_company_finder
  output_file: output/trending_companies.md

research_trending_companies:
  description: >
    Given the list of trending companies, provide a detailed research report on each one.
    For each company, include:
      - Company name
      - Current market position and competition
      - Future outlook and growth prospects
      - Investment potential and suitability for investors
    Format the output as a structured Markdown report with clear sections for each company.
  expected_output: >
    A detailed Markdown research report with sections for each company, including
    market position, future outlook, and investment potential.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.md

pick_best_company:
  description: >
    Analyze the research findings and pick the single best company for investment.
    First, provide a brief push-notification-style summary with the decision and a 
    one-sentence rationale.
    Then, provide a detailed Markdown report explaining:
      - Why this company was chosen
      - Why the other companies were not selected
  expected_output: >
    A Markdown report with:
    - The chosen company and why it was chosen
    - The companies that were not selected and why they were not selected
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
